//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyThuvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoThongKe
    {
        public int MaBaoCao { get; set; }
        public System.DateTime NgayBaoCao { get; set; }
        public Nullable<int> TongSoSach { get; set; }
        public Nullable<int> TongSoSachMuon { get; set; }
        public Nullable<int> TongSoSachTra { get; set; }
        public Nullable<int> TongSoDocGia { get; set; }
        public string GhiChu { get; set; }
    }
}
