//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyThuvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuonTra
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaMuonTra { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> So_Luong { get; set; }
    
        public virtual MuonTra MuonTra { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
