//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyThuvien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MuonTra()
        {
            this.ChiTietPhieuMuonTras = new HashSet<ChiTietPhieuMuonTra>();
        }
    
        public int MaMuonTra { get; set; }
        public Nullable<int> MaDocGia { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuMuonTra> ChiTietPhieuMuonTras { get; set; }
        public virtual DocGia DocGia { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
